console.log("-----------------------IPv4------------------------")
console.log("Http Hunt: node http.js <IP> <THREADS> <TIME>");
console.log("Https Hunt: node https.js <IP> <THREADS> <TIME>")
console.log("Udp Nuke: node udpnuke.js <IP> <PORT> <SIZE> <TIME>")
console.log("Tcp Flood: node tcpflood.js <IP> <PORT> <SIZE> <TIME>")
console.log("Dns Flood: node dns.js <IP> <PORT> <SIZE> <TIME>")
console.log("Tls Flood: node tls.js <HOST> <PORT> <TIME>")
console.log("Syn Flood: node syn.js <IP> <PORT> <TIME   >")
console.log("FiveM: node fivem.js <IP> <PORT> <SIZE> <TIME>")
console.log("Minecraft: node minecraft.js <IP> <PORT> <SIZE> <TIME>")
console.log()
console.log("-----------------------IPv6------------------------")
console.log("Udp6 Flood: node udp6.js <IP> <PORT> <SIZE> <TIME>")
console.log("Syn6 Flood: node syn6.js <IP> <PORT> <TIME>")
console.log()
console.log("----------------------Message----------------------")
console.log("node msg.js <TCP OR UDP> <IP> <PORT> <MESSAGE> ")
console.log()
console.log("---------------------Universal---------------------")
console.log("Comp: node comp.js")